FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN npx prisma generate

EXPOSE 4000

CMD ["yarn", "workspace", "gateway", "dev"]